### ISSUE TITLE
Support for ES Modules (Import and Export) in Node configuration

### ISSUE THREAD

**Issue by dvalentiate** [bluedrop-learning-networks/eslint-config-bluedrop#60]
When trying to use import in a nodejs project I get the following eslint error:

> Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

I tried working around this by putting the following in `eslintrs.js`:

```
	parserOptions: {
		sourceType: 'module',
	},
```

But now none of the linting is working and no errors are returned for problems.

I'm not sure what would be involved to support modules linting with node in but I'm hoping for it.

**Comment by MitMaro** [comment]
I'm really not sure what to do about this.

ESLint is moving/has moved towards supporting ESM, but the `sourceType` still defaults to "script". See: https://github.com/eslint/rfcs/pull/43/files

My only thought was to add a configuration for ESM that would set the `parserOptions` correctly and potentially adjust any rules that would require modification for ESM.

Right now you can kinda get that with the babel configuration, but that doesn't really work for a pure Node.js code base.

I personally would just like to migrate everything to ESM since the syntax is a lot better than CommonJS require calls, but that wouldn't be a small migration.

**Comment by dvalentiate** [comment]
I think we can close this issue for now. It will reappear but might as well wait for the ecosystem as a whole to mature a bit around this and see what comes up when we have more of a need.
